### ISSUE TITLE
[Question]: Create an api token for user without admin/manager permissions

### ISSUE THREAD

**Issue by SimonErich** [awork-io/awork#65] opened 2022-09-02 14:48 UTC
### What is your question?

Hello,

Is there a way to get an api key for my account, even if I am not a manager or admin?
We have an application, that can integrate with awork and sync our time entries into it.
This instance here is our clients instance and they therefore can't give me manager access.

The problem is, that I still need to access the tasks and sync them into our budget application and sync back the time.

I also cannot use username+password auth, because on our clients instance they enforce signle sign on. I already tried to change my password, so I could login like that, but that doesn't work either (according to your support colleguea who I asked about this)

What could I do, to be able to access the data programatically?

Can you maybe create a token for my user?
Or worst case: could you reset my password, so I can use the api via username + password?

**Comment by nilzzzzzz** [comment] 2022-09-05 10:25
Hi @SimonErich, 

not sure if i understand your request completely. So if you are no admin in the workspace the only way is that you implement the oauth flow (you still need a client id and a client secret). But for the rest of the oauth flow you can the use the login mechanism which you are using when you login to awork as a user.

Does that help?

Nils

**Comment by DmitrySidorenkoShim** [comment] 2022-09-30 12:39
Hi @nilzzzzzz 

I tried this with OAuth 2 on demo trial project.
and it works perfect with `client_id`, `client_secret` (and also `redirect_uri`).

The problem is we can't get `client_id`, `client_secret` right now from the Client...

Is it possible to get access to api without these data?
At least read only.
maybe we can get Bearer token from browser and use it with api?
or something similar?
The only we have now is login and password.

Best regards
Dimon

**Comment by nilzzzzzz** [comment] 2022-10-05 20:31
Hi @DmitrySidorenkoShim ,

with client you mean your customer and not an application client, right?
Unfortunately there is no way to use the oauth flow without the client_id & client_secret. Why is it not possible that the client  creates a client_id & client_secret for you? There should be no risk for him, because you are using your credentials to login to awork.

Best

Nils

**Comment by DmitrySidorenkoShim** [comment] 2022-10-05 21:07
Hi @nilzzzzzz 

Thank you very much for the answer and for info.
We finally got from our Customer `client_id`, `client_secret` and `redirect_url`.
We also successfully created a token.
And it works perfect for api calls.

Only one last question: can you tell how much time is it valid?

Thanks in advance.

Dimon

**Comment by nilzzzzzz** [comment] 2022-10-07 10:48
Hi @DmitrySidorenkoShim 

the access token lifetime is 24 hours. Then you need to get a new access token by using the refresh token.

Best

Nils

**Comment by DmitrySidorenkoShim** [comment] 2022-10-07 13:58
Hi @nilzzzzzz 

Sorry to bother you again
but I have one more issue.

For get 'authorization_code' request
everything works perfect
and I got in response:

```
{
  "scope": "offline_access",
  "token_type": "Bearer",
  "access_token": "eyJhbGciO...",
  "expires_in": 86400,
  "refresh_token": "eyJhb..."
}
```

BUT for 'refresh_token' request
I am getting this response:

```
{
  "token_type": "Bearer",
  "access_token": "eyJhbGci...",
  "expires_in": 86400
}
```

So, as you can see NO 'refresh_token' in second response
and basically we would need to get 'access_token' manually each 48 hours...
(we can refresh token only once)

Is it possible to add 'refresh_token' property for 'refresh_token' request?
I would help us so much
because we need to call api each day (maybe couple times) by cron job.

Best regards

Dimon

**Comment by nilzzzzzz** [comment] 2022-10-07 14:08
@DmitrySidorenkoShim 

it's easier. You can refresh the access token within 30 days, even after the access token was expired. 
So what you  can do:
You do the api call which you want to do. Then if you get a response that the access token is expired you do the refresh token call and automatically the refresh token expiration is extended again to 30 days and the old refresh token is valid. 
Not issuing new refresh tokens but extending the lifetime is recommended because otherwise you can run into race conditions with parallel refresh token calls.

Hope that helps.

nils

**Comment by DmitrySidorenkoShim** [comment] 2022-10-10 08:36
@nilzzzzzz 

Thank you very much for quick reply.
I am sure this refresh token expiration in 30 days will perfectly fits in our process.

Thanks again for your time and information.
This helped a-lot.
I think we can close this issue.

Dimon

**Comment by nilzzzzzz** [comment] 2022-10-10 08:48
@DmitrySidorenkoShim perfect! have a great week!

**Closed by nilzzzzzz** 2022-10-10 08:48 UTC
Labels: question
